### ISSUE TITLE
Yo.

### ISSUE THREAD

**Issue by vanility0001** [gocord/gocord#3]
Sup.
This is my issue, NOT WRITTEN Python. But at least its not JS (LOL LOL JS)

**Comment by vanility0001** [comment]
Thank you.

**Comment by af280cf94190a54043e947948a0031ce7ed71dc** [comment]
I believe this is a user-end error and we cannot solve this.

**Comment by vanility0001** [comment]
Right, you, need to get your head, out your backside, and get real...
